name: Build CLI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - parallel:
          - run: bun dedupe --check
          - run: bunx eslint
          - run: bunx tsc
          - run: bun run test
          - run: bun run build
      - uses: actions/upload-artifact@v7
        with:
          name: cli
          path: cli
