name: Schedule

on:
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v23
        with:
          name: cli
          workflow: build.yml
      - run: chmod +x cli
      - run: ./cli
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
